{% set name = "mysqlclient" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e80109b0ae8d952b900b31b623181532e5e89376d707dcbeb63f99e69cefe559

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - mysql-connector-c
  run:
    - python
    - mysql-connector-c

test:
  imports:
    - MySQLdb
    - MySQLdb.constants
    - MySQLdb.cursors

about:
  home: https://github.com/PyMySQL/mysqlclient-python
  doc_url: https://mysqlclient.readthedocs.io/
  license: GPL-2.0
  license_file: LICENSE
  summary: 'Python interface to MySQL'

extra:
  recipe-maintainers:
    - halldc
