{% set name = "mysqlclient" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c7ad15b87293b12fd44b47c46879ec95ec647f4567e866ccd70b8337584e9b2

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    # provides mysql-libs via a run_export
    - mysql-devel
  run:
    - python

test:
  imports:
    - MySQLdb
    - MySQLdb.constants
    - MySQLdb.cursors

about:
  home: https://github.com/PyMySQL/mysqlclient-python
  doc_url: https://mysqlclient.readthedocs.io/
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Python interface to MySQL

extra:
  recipe-maintainers:
    - jimbudarz
    - halldc
