{% set name = "mysqlclient" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 04368445f9c487d8abb7a878e3d23e923e6072c04a6c320f9e0dc8a82efba14e

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  script_env:
    - MYSQLCLIENT_CONNECTOR={{ LIBRARY_PREFIX }}  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    # provides mysql-libs via a run_export
    - mysql-devel
    - mariadb-connector-c ==3.3.5  # [win]
  run:
    - python

test:
  imports:
    - MySQLdb
    - MySQLdb.constants
    - MySQLdb.cursors

about:
  home: https://github.com/PyMySQL/mysqlclient-python
  doc_url: https://mysqlclient.readthedocs.io/
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Python interface to MySQL

extra:
  recipe-maintainers:
    - jimbudarz
    - halldc
